#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ -z "${LINUX_SRC:-}" ]]; then
  echo "LINUX_SRC must point to a Linux kernel source tree" >&2
  exit 2
fi

LINUX_SRC="$(cd "${LINUX_SRC}" && pwd)"
LINUX_BUILD="${LINUX_BUILD:-${ROOT}/build/linux-${ARCH:-x86_64}}"
ARCH="${ARCH:-x86_64}"
CC="${CC:-gcc}"
JOBS="${JOBS:-$(nproc 2>/dev/null || echo 2)}"
CBMC_BIN="${CBMC:-cbmc}"
GOTO_CC_BIN="${GOTO_CC:-goto-cc}"
GOTO_INSTRUMENT_BIN="${GOTO_INSTRUMENT:-goto-instrument}"

SOCKET_I="${LINUX_BUILD}/net/socket.i"
PROOF_BUILD="${ROOT}/build/proofs/net_socket_sys_socket/real_linux_${ARCH}"
CONSTANTS_H="${PROOF_BUILD}/socket_contracts_kernel_constants.h"
SANITIZED_SOCKET_I="${PROOF_BUILD}/socket.cbmc.i"
REAL_SLICE_C="${PROOF_BUILD}/net_socket_real_slice.c"
COMBINED_C="${PROOF_BUILD}/net_socket_real_combined.c"
COMBINED_GOTO="${PROOF_BUILD}/net_socket_real_combined.goto"
REPLACED_GOTO="${PROOF_BUILD}/net_socket_real_replaced.goto"
SLICED_GOTO="${PROOF_BUILD}/net_socket_real_sliced.goto"

mkdir -p "${LINUX_BUILD}" "${PROOF_BUILD}"

echo "Preparing Linux tree: ${LINUX_SRC}"
if [[ ! -f "${LINUX_BUILD}/.config" ]]; then
  make -C "${LINUX_SRC}" O="${LINUX_BUILD}" ARCH="${ARCH}" CC="${CC}" defconfig
fi
make -C "${LINUX_SRC}" O="${LINUX_BUILD}" ARCH="${ARCH}" CC="${CC}" olddefconfig
make -C "${LINUX_SRC}" O="${LINUX_BUILD}" ARCH="${ARCH}" CC="${CC}" -j"${JOBS}" prepare scripts

echo "Generating Kbuild preprocessed source: net/socket.i"
make -C "${LINUX_SRC}" O="${LINUX_BUILD}" ARCH="${ARCH}" CC="${CC}" V=1 net/socket.i
test -f "${SOCKET_I}"

echo "Extracting socket constants from Kbuild output"
python3 "${ROOT}/scripts/extract-socket-constants-from-preprocessed.py" \
  "${SOCKET_I}" "${CONSTANTS_H}"

echo "Sanitizing Kbuild preprocessed source for CBMC frontend compatibility"
python3 "${ROOT}/scripts/sanitize-kernel-preprocessed-for-cbmc.py" \
  "${SOCKET_I}" "${SANITIZED_SOCKET_I}" \
  --report "${PROOF_BUILD}/sanitize-report.txt"

echo "Extracting socket proof slice from Kbuild preprocessed source"
python3 "${ROOT}/scripts/extract-socket-proof-slice-from-preprocessed.py" \
  "${SANITIZED_SOCKET_I}" "${REAL_SLICE_C}"

echo "Building combined real-source proof translation unit"
{
  printf '/* Generated by scripts/run-real-linux-socket-proof.sh. */\n'
  printf '/* Source: %s */\n' "${SOCKET_I}"
  cat "${REAL_SLICE_C}"
  printf '\n#line 1 "%s"\n' "${ROOT}/verification/cbmc/proofs/net_socket_sys_socket/real_harness_tail.c"
  cat "${ROOT}/verification/cbmc/proofs/net_socket_sys_socket/real_harness_tail.c"
} >"${COMBINED_C}"

echo "Compiling real-source proof with goto-cc"
"${GOTO_CC_BIN}" \
  -std=gnu11 \
  -fms-extensions \
  -I "${PROOF_BUILD}" \
  -c "${COMBINED_C}" \
  -o "${COMBINED_GOTO}"

echo "Replacing proof-boundary calls with socket contracts"
"${GOTO_INSTRUMENT_BIN}" \
  --replace-calls sock_create:socket_model_sock_create \
  --replace-calls sock_map_fd:socket_model_sock_map_fd \
  "${COMBINED_GOTO}" "${REPLACED_GOTO}"

echo "Keeping the extracted proof slice intact"
cp "${REPLACED_GOTO}" "${SLICED_GOTO}"

echo "Running CBMC over real-source socket proof"
"${CBMC_BIN}" \
  "${SLICED_GOTO}" \
  --function main \
  --object-bits 12 \
  --unwind 1 \
  --bounds-check \
  --pointer-check \
  --signed-overflow-check \
  --unsigned-overflow-check \
  --conversion-check \
  --div-by-zero-check \
  --pointer-overflow-check \
  --trace \
  --stop-on-fail \
  | tee "${PROOF_BUILD}/cbmc.txt"

grep -q "VERIFICATION SUCCESSFUL" "${PROOF_BUILD}/cbmc.txt"
