#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ -z "${LINUX_SRC:-}" ]]; then
  echo "LINUX_SRC must point to a Linux kernel source tree" >&2
  exit 2
fi

LINUX_SRC="$(cd "${LINUX_SRC}" && pwd)"
LINUX_BUILD="${LINUX_BUILD:-${ROOT}/build/linux-${ARCH:-x86_64}}"
ARCH="${ARCH:-x86_64}"
CC="${CC:-gcc}"
JOBS="${JOBS:-$(nproc 2>/dev/null || echo 2)}"
CBMC_BIN="${CBMC:-cbmc}"
GOTO_CC_BIN="${GOTO_CC:-goto-cc}"
GOTO_INSTRUMENT_BIN="${GOTO_INSTRUMENT:-goto-instrument}"

SOCKET_I="${LINUX_BUILD}/net/socket.i"
PROOF_BUILD="${ROOT}/build/proofs/net_sendmsg_control_bughunt/real_linux_${ARCH}"
CONSTANTS_H="${PROOF_BUILD}/socket_contracts_kernel_constants.h"
SANITIZED_SOCKET_I="${PROOF_BUILD}/socket.cbmc.i"
REAL_SLICE_C="${PROOF_BUILD}/net_sendmsg_control_bughunt_slice.c"
COMBINED_C="${PROOF_BUILD}/net_sendmsg_control_bughunt_combined.c"
COMBINED_GOTO="${PROOF_BUILD}/net_sendmsg_control_bughunt_combined.goto"
INSTRUMENTED_GOTO="${PROOF_BUILD}/net_sendmsg_control_bughunt_instrumented.goto"

mkdir -p "${LINUX_BUILD}" "${PROOF_BUILD}"

echo "Preparing Linux tree: ${LINUX_SRC}"
if [[ ! -f "${LINUX_BUILD}/.config" ]]; then
  make -C "${LINUX_SRC}" O="${LINUX_BUILD}" ARCH="${ARCH}" CC="${CC}" defconfig
fi
make -C "${LINUX_SRC}" O="${LINUX_BUILD}" ARCH="${ARCH}" CC="${CC}" olddefconfig
make -C "${LINUX_SRC}" O="${LINUX_BUILD}" ARCH="${ARCH}" CC="${CC}" -j"${JOBS}" prepare scripts

echo "Generating Kbuild preprocessed source: net/socket.i"
make -C "${LINUX_SRC}" O="${LINUX_BUILD}" ARCH="${ARCH}" CC="${CC}" V=1 net/socket.i
test -f "${SOCKET_I}"

echo "Extracting socket/sendmsg constants from Kbuild output"
python3 "${ROOT}/scripts/extract-socket-constants-from-preprocessed.py" \
  "${SOCKET_I}" "${CONSTANTS_H}"

echo "Sanitizing Kbuild preprocessed source for CBMC frontend compatibility"
python3 "${ROOT}/scripts/sanitize-kernel-preprocessed-for-cbmc.py" \
  "${SOCKET_I}" "${SANITIZED_SOCKET_I}" \
  --report "${PROOF_BUILD}/sanitize-report.txt"

echo "Extracting ____sys_sendmsg control-buffer bug-hunt slice"
PYTHONPATH="${ROOT}/scripts${PYTHONPATH:+:${PYTHONPATH}}" \
python3 "${ROOT}/scripts/extract-sendmsg-control-bughunt-slice-from-preprocessed.py" \
  "${SANITIZED_SOCKET_I}" "${REAL_SLICE_C}"

echo "Building combined bug-hunt translation unit"
{
  printf '/* Generated by scripts/run-real-linux-sendmsg-control-bughunt.sh. */\n'
  printf '/* Source: %s */\n' "${SOCKET_I}"
  cat "${REAL_SLICE_C}"
  printf '\n#line 1 "%s"\n' "${ROOT}/verification/cbmc/proofs/net_sendmsg_control_bughunt/bughunt_tail.c"
  cat "${ROOT}/verification/cbmc/proofs/net_sendmsg_control_bughunt/bughunt_tail.c"
} >"${COMBINED_C}"

echo "Compiling bug-hunt proof with goto-cc"
"${GOTO_CC_BIN}" \
  -std=gnu11 \
  -fms-extensions \
  -I "${PROOF_BUILD}" \
  -c "${COMBINED_C}" \
  -o "${COMBINED_GOTO}"

echo "Cleaning inline assembler statements"
"${GOTO_INSTRUMENT_BIN}" \
  "${COMBINED_GOTO}" "${INSTRUMENTED_GOTO}"

echo "Running CBMC bug hunt over ____sys_sendmsg control-buffer paths"
"${CBMC_BIN}" \
  "${INSTRUMENTED_GOTO}" \
  --function main \
  --object-bits 12 \
  --unwind 2 \
  --bounds-check \
  --pointer-check \
  --signed-overflow-check \
  --unsigned-overflow-check \
  --conversion-check \
  --div-by-zero-check \
  --pointer-overflow-check \
  --trace \
  --stop-on-fail \
  | tee "${PROOF_BUILD}/cbmc.txt"

if grep -q "VERIFICATION SUCCESSFUL" "${PROOF_BUILD}/cbmc.txt"; then
  echo "No counterexample found in this bounded sendmsg control-buffer profile."
else
  echo "Counterexample found; triage build/proofs/net_sendmsg_control_bughunt." >&2
  exit 1
fi
